### ISSUE TITLE
extract strings only matches Calc commands

### ISSUE THREAD

**Issue by pmrowla** [Stefan311/pylivemaker-tools#1]
If you are translating string literals in Calc commands (for variable assignment, string concat, etc) for a lot of games you will also need to translate the same literals in non-Calc command conditional statements (like If, Elseif, While, Jump, Call).

Basically similar to how you need to translate strings for menu choices in two places: where the choice string is set, and where it is checked with the `SEL == "some string"` jump condition

where you have
```py
    for c in lsb.commands:
        if c.type == CommandType.Calc:
            for s in c.args["Calc"]["entries"]:
                op = s["operands"][0]
                if op["type"] == "Str":
                    csv_data.append(["pylm:string:{}:{}:{}".format(lsb_file, c.LineNo, s["name"]), None, c, op["value"]])
```

you probably want
```py
    for c in lsb.commands:
        calc = c.get("Calc")
        if calc:
            for s in calc["entries"]:
                op = s["operands"][0]
                if op["type"] == "Str":
                    csv_data.append(["pylm:string:{}:{}:{}".format(lsb_file, c.LineNo, s["name"]), None, c, op["value"]])
```
since livemaker always uses `Calc` as the field name for a conditional.

Even with this change it still doesn't cover every command which can contain string literals, but it at least covers all the common "set var to string" and "conditional based on whether or not var matches string" cases which should probably be good enough for translation purposes.

(if you just search for `LiveParser` and `LiveParserArray` in `lsb/commands.py` you'll see what I mean about not covering all the possible places for string literals, but it's unlikely that a majority of those commands will matter for game translation)

**Comment by Stefan311** [comment]
Good advice. Thanks.
