### ISSUE TITLE
Help with usage your tool!

### ISSUE THREAD

**Issue by mehmeh1z** [Stefan311/pylivemaker-tools#2]
Hi!
Could you please tell me how to use googletranslate.py.
Here I have already a .csv file which I got thanks to pylivemaker. So how can I use your tool to translate it?
Your readme doesn't say anything about it, so I thought I'd ask here at least, since I obviously can't figure it out on my own.

**Comment by Stefan311** [comment]
Hi,
I suspect googletranslate.py does not work anymore. It uses a non-payed inofficial API, so google can change (or even delete) it anytime, what they do very often. To keep my program working, I would have to change it too. This I am not going to do. Sorry.

I would suggest the use of translator++, a tool who can also import CSV files, and translate it on several engines.
https://dreamsavior.net/translator-plusplus/
The developer of translate++ keeps track of the API madness much better than I am able to do.

greetings
Stefan
